domain: 99point99.github.io
url: https://99point99.github.io
baseurl: /web/
title: 99POINT99 CRM Notebook
description: A personal site showcasing CRM code and solutions
sitefolder: web
theme: jekyll-theme-minimal
